version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=anatolii
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pinky
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
    driver: local
